import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar/SideBar";
import NprogressProviders from "./lib/NextNprogress";
import Providers from "./lib/ThemeProviders";



const poppins = Poppins({
  subsets: ["latin", "latin-ext"],
  weight: ["300", "700"],
});

export const metadata: Metadata = {
  title: "IndoxJudge",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} `}
        
      >
        <Providers>
          <NprogressProviders>
          <div className="bg-gradient-to-bl flex md:justify-between  from-[#d8ddde] to-[#f9fafa] dark:bg-[#57595c] dark:text-white w-screen h-screen">
            <SideBar />
            {children}
            </div>
          </NprogressProviders>
        </Providers>
      </body>
    </html>
  );
}
